// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvPbSiqXqiVBKtWe6j2nIqGoQ0rwsXCW0',
    appId: '1:126450183989:web:964096e3ecaa865879667c',
    messagingSenderId: '126450183989',
    projectId: 'flashenglish-af7d1',
    authDomain: 'flashenglish-af7d1.firebaseapp.com',
    storageBucket: 'flashenglish-af7d1.firebasestorage.app',
    measurementId: 'G-LR47K6VXMG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHAaL4MCO9YGifI4d2jNHZtr7u9tKooy8',
    appId: '1:126450183989:android:3af22af059bef9ae79667c',
    messagingSenderId: '126450183989',
    projectId: 'flashenglish-af7d1',
    storageBucket: 'flashenglish-af7d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_NKR3y0_pRIwhUGWhNix6xOpIEYOW22s',
    appId: '1:126450183989:ios:d006a52b5602c6d979667c',
    messagingSenderId: '126450183989',
    projectId: 'flashenglish-af7d1',
    storageBucket: 'flashenglish-af7d1.firebasestorage.app',
    androidClientId:
        '126450183989-qriijdg48bo91664non7581hsgmn3v2t.apps.googleusercontent.com',
    iosClientId:
        '126450183989-fogmm5ajmeoi60dhmcv7g9qhq8kn04pt.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashEnglish',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_NKR3y0_pRIwhUGWhNix6xOpIEYOW22s',
    appId: '1:126450183989:ios:d006a52b5602c6d979667c',
    messagingSenderId: '126450183989',
    projectId: 'flashenglish-af7d1',
    storageBucket: 'flashenglish-af7d1.firebasestorage.app',
    androidClientId:
        '126450183989-qriijdg48bo91664non7581hsgmn3v2t.apps.googleusercontent.com',
    iosClientId:
        '126450183989-fogmm5ajmeoi60dhmcv7g9qhq8kn04pt.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashEnglish',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvPbSiqXqiVBKtWe6j2nIqGoQ0rwsXCW0',
    appId: '1:126450183989:web:717faf28fad6d73e79667c',
    messagingSenderId: '126450183989',
    projectId: 'flashenglish-af7d1',
    authDomain: 'flashenglish-af7d1.firebaseapp.com',
    storageBucket: 'flashenglish-af7d1.firebasestorage.app',
    measurementId: 'G-7MKBYKY6DW',
  );
}
